services:
  seaf-backend:
    container_name: seaf-backend
    build:
      context: seaf-backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
        VUE_APP_PLANTUML_SERVER: ${VUE_APP_PLANTUML_SERVER}
        VUE_APP_DOCHUB_ROLES_MODEL: ${VUE_APP_DOCHUB_ROLES_MODEL}
        VUE_APP_DOCHUB_AUTHORITY_SERVER: ${VUE_APP_DOCHUB_AUTHORITY_SERVER}
        VUE_APP_DOCHUB_AUTHORITY_CLIENT_ID: ${VUE_APP_DOCHUB_AUTHORITY_CLIENT_ID}
    env_file:
      - .env
    ports:
      - "8080:3030"
    volumes:
      - ./seaf-backend/roles:/var/www/public/roles/:ro
      - /var/archportal/workspace:/var/www/public/workspace/:ro

  plantuml:
    container_name: plantuml
    image: seaf/plantuml-server:jetty
    ports:
      - "8079:8080"

