#version: '1'
services:
  seaf-backend:
    container_name: seaf-backend
    build:
      context: seaf-backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    environment:
      VUE_APP_DOCHUB_MODE: backend
      VUE_APP_DOCHUB_BACKEND_PORT: 3030
      VUE_APP_DOCHUB_METAMODEL: metamodel/root.yaml
      VUE_APP_DOCHUB_ROOT_MANIFEST: workspace/root.yaml
      VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS: n
      VUE_APP_PLANTUML_SERVER: archportal.local/svg/

    env_file:
      - ./seaf-backend/.env
    ports:
      - "8080:3030"
    volumes:
      - /var/archportal/workspace:/var/www/public/workspace:ro
#      - /var/archportal/roles:/var/www/public/roles:ro

#  seaf-frontend:
#    container_name: seaf-frontend
#    build:
#      context: seaf-frontend
#      dockerfile: Dockerfile
#    # volumes:
#    #   - ./frontend/nginx.conf:/etc/nginx/nginx.conf
#    environment:
#      # т.к. это будет использоваться в браузере, поэтому нужен внешний URL
#      # ссылаемся на себя же, в nginx проксируемся в backend
#      NGINX_BACKEND_LOCATION: http://seaf-backend:3030
#      VUE_APP_DOCHUB_BACKEND_URL: http://localhost:3030/ # прямой ход в backend - http://localhost:3030
#      VUE_APP_DOCHUB_ROOT_DOCUMENT: dochub.welcome
#      VUE_APP_PLANTUML_SERVER: http://archportal.local/svg/
#    ports:
#      - "8080:80"

  plantuml:
    container_name: plantuml
    image: seaf/plantuml-server:jetty
    ports:
      - "8079:8080"

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    env_file:
      - ./reverse-proxy/env/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/templates:/etc/nginx/templates
      - ./reverse-proxy/pki:/etc/nginx/pki