#version: '1'
services:
  seaf-backend:
    build:
      context: seaf-backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    environment:
      VUE_APP_DOCHUB_MODE: backend
      VUE_APP_DOCHUB_BACKEND_PORT: 3030
      VUE_APP_DOCHUB_ROLES_MODEL: y
      VUE_APP_DOCHUB_METAMODEL: metamodel/root.yaml
      VUE_APP_DOCHUB_ROOT_MANIFEST: workspace/root.yaml
      VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS: n
      VUE_APP_PLANTUML_SERVER: archportal.local/svg/
      VUE_APP_DOCHUB_ROLES: file:///roles/default.yaml
      VUE_APP_DOCHUB_AUTHORITY_SERVER: http://archaaa.local:8082/realms/archportal
      VUE_APP_DOCHUB_AUTHORITY_CLIENT_ID: archportal
      VUE_APP_DOCHUB_AUTH_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9WhNBLOUKeq6xpPNfgZhhXDbEl+8bI3bTRBDdHFkAEmK6wIpSL1uvzlsvWFCoX79I7hZURUEj4zSaQ/7cD0Pe4z3VqnJKbXhcKBy552t3f/6vgBvMR2WQ4TVJIu8xWeGSghjs85nSJYK4boLzbb0SfZREoIE/EJYvCV/XJACHakq9hQcmAwJCPanPmFjibUpNdRJVTFMC/n/jKB2Q1PeeyNAS0Xuef6KvGQpjwydKgJD9WwAEnAj+24npgq7lUMiCJK18UcNQcbAEXtNSN1e3I9MK0h6Uv8sDJmMqz/MarWj9Q/Q/QyMBFr5i/hlgw7QgEjxSqvud7dFBlbE/JMk4QIDAQAB-----END PUBLIC KEY-----
    env_file:
      - ./seaf-backend/.env
    ports:
      - "8080:3030"
    volumes:
      - /var/archportal:/var/www/public/workspace:ro

#  seaf-frontend:
#    container_name: seaf-frontend
#    build:
#      context: seaf-frontend
#      dockerfile: Dockerfile
#    # volumes:
#    #   - ./frontend/nginx.conf:/etc/nginx/nginx.conf
#    environment:
#      # т.к. это будет использоваться в браузере, поэтому нужен внешний URL
#      # ссылаемся на себя же, в nginx проксируемся в backend
#      NGINX_BACKEND_LOCATION: http://seaf-backend:3030
#      VUE_APP_DOCHUB_BACKEND_URL: http://localhost:3030/ # прямой ход в backend - http://localhost:3030
#      VUE_APP_DOCHUB_ROOT_DOCUMENT: dochub.welcome
#      VUE_APP_PLANTUML_SERVER: http://archportal.local/svg/
#      VUE_APP_DOCHUB_RENDER_CORE: ELK
#    ports:
#      - "8080:80"

  plantuml:
    image: seaf/plantuml-server:jetty
    container_name: plantuml
    ports:
      - "8079:8080"

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    build:
      context: reverse-proxy
    env_file:
      - ./reverse-proxy/env/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/templates:/etc/nginx/templates
      - ./reverse-proxy/pki:/etc/nginx/pki