#version: '1'
services:
  seaf-backend:
    container_name: seaf-backend
    build:
      context: seaf-backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    environment:
      VUE_APP_DOCHUB_BACKEND_PORT: 3030
      VUE_APP_DOCHUB_METAMODEL: metamodel/root.yaml
#      VUE_APP_DOCHUB_ROOT_MANIFEST: workspace/root.yaml
      VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS: n
      VUE_APP_PLANTUML_SERVER: archportal.local/svg/
      VUE_APP_DOCHUB_ROLES: file:///roles/roles.yaml
      VUE_APP_DOCHUB_GITLAB_URL: http://archgitlab.local:8929/
      VUE_APP_DOCHUB_ROOT_MANIFEST: gitlab:1:main@root.yaml
      VUE_APP_DOCHUB_PERSONAL_TOKEN: glpat-aK63GG4xZFxWcyFM2ixn
#      VUE_APP_DOCHUB_AUTHORITY_SERVER: http://archaaa.local:8081/realms/archportal
#      VUE_APP_DOCHUB_AUTHORITY_CLIENT_ID: archportal
      VUE_APP_DOCHUB_AUTH_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3vQQfcfSayGGkEXJQIrVrXIl8iK3/AnwV4KkR2G5T1Ka6abBEosbVJS2kS09Fxo84AuFb3jgbXGYJvMiisBTdK5Q3nUqZZGoapR9AkIx5LKTWAAQF5QYc+vUIDZoX5S1MnTdnOGvP8j4jZpH5fgnwc4mXKrxuxWBYEsJiI9lP9rAvowWUKQ7z+AAvqXDFbdymxxsWYPXe092GcOY1PWOmNal8DJxA64uRqWzCb7RYVUMD8nfT5pKfhrka3sCE/gYPSsvxT5s3NSi8fETHi6MdtvXtdNReapJ95ngPoeh9Ug52pk8TiAwmTvi1c25c1vxTYF9QkJLae8WZy4XQDIuHwIDAQAB-----END PUBLIC KEY-----
    env_file:
      - ./seaf-backend/.env
    ports:
      - "8080:3030"
    volumes:
      - /var/archportal/workspace:/var/www/public/workspace/:ro
      - /var/archportal/roles:/var/www/public/roles:ro

  plantuml:
    container_name: plantuml
    image: seaf/plantuml-server:jetty
    ports:
      - "8079:8080"

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    env_file:
      - ./reverse-proxy/env/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/templates:/etc/nginx/templates
      - ./reverse-proxy/pki:/etc/nginx/pki