version: "3.9"

services:
  postgres:
    build:
      context: dockerfiles
      dockerfile: postgres.dockerfile
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 15s
      retries: 5
    env_file:
      - ./env/postgres.env
    ports:
      -  '127.0.0.1:5432:5432'
    networks:
      - application

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start
    env_file:
      - ./env/keycloak.env
    ports:
      - 8081:80
      - 8443:443
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application
    volumes:
      - ../certs/server.crt:/opt/keycloak/conf/server.crt:ro
      - ../certs/server.key:/opt/keycloak/conf/server.key:ro

networks:
  application:
    name: network