version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: 'git.archportal.local'
    environment:
      # nginx[‘listen_port’] = 80
      # nginx[‘listen_https’] = false
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.archportal.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        puma['worker_processes'] = 0

        sidekiq['concurrency'] = 10

        prometheus_monitoring['enable'] = false

        gitlab_rails['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        }

        gitaly['configuration'] = {
          concurrency: [
            {
              'rpc' => "/gitaly.SmartHTTPService/PostReceivePack",
              'max_per_repo' => 3,
            }, {
              'rpc' => "/gitaly.SSHService/SSHUploadPack",
              'max_per_repo' => 3,
            },
          ],
          cgroups: {
            repositories: {
              count: 2,
            },
            mountpoint: '/sys/fs/cgroup',
            hierarchy_root: 'gitaly',
            memory_bytes: 500000,
            cpu_shares: 512,
          },
        }
        gitaly['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000',
          'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
        }
    ports:
      - '8929:80'
#      - '8843:443'
      - '2424:22'
#      - '8083:8929'
    volumes:
       -  ./mount/config:/etc/gitlab
       -  ./mount/logs:/var/log/gitlab
       -  ./mount/data:/var/opt/gitlab
    shm_size: '256m'