# syntax=docker/dockerfile:1.3
FROM node:20-alpine as pre
WORKDIR /seaf-archtool-core
COPY seaf-archtool-core/plugins /docker-context/seaf-archtool-core/plugins
RUN cd /docker-context/; \
    find seaf-archtool-core/plugins -name "package.json" -mindepth 0 -maxdepth 4 -exec cp --parents "{}" / \;


FROM node:20-alpine as build

WORKDIR /seaf-archtool-core
ENV PATH /seaf-archtool-core/node_modules/.bin:$PATH
RUN npm install -g recursive-install
COPY ./seaf-archtool-core/package.json /seaf-archtool-core/package.json
COPY ./seaf-archtool-core/package-lock.json /seaf-archtool-core/package-lock.json

COPY --from=pre /seaf-archtool-core/ /seaf-archtool-core/

RUN cd /seaf-archtool-core/plugins && npx recursive-install --skip-root

RUN npm install

COPY ./seaf-archtool-core /seaf-archtool-core/

ENV VUE_APP_DOCHUB_BACKEND_URL=\${VUE_APP_DOCHUB_BACKEND_URL}
ENV VUE_APP_DOCHUB_ROOT_DOCUMENT=\${VUE_APP_DOCHUB_ROOT_DOCUMENT}
ENV VUE_APP_DOCHUB_JSONATA_ANALYZER=\${VUE_APP_DOCHUB_JSONATA_ANALYZER}
ENV VUE_APP_PLANTUML_SERVER=\${VUE_APP_PLANTUML_SERVER}
ENV VUE_APP_DOCHUB_RENDER_CORE=\${VUE_APP_DOCHUB_RENDER_CORE}

RUN npm run build


FROM nginx:1.24.0-alpine as prod

WORKDIR /web

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /seaf-archtool-core/dist .

COPY ./entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]