services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    env_file:
      - ./env/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates/routing.conf.template:/etc/nginx/templates/routing.conf.template:ro
      - ./certs:/etc/nginx/pki
